/**
 * Core domain types for the AI SAT tutor.
 *
 * The SAT (digital, 2026) has two main sections:
 *  - Reading & Writing (R&W)
 *  - Math
 * Each section is split into modules; this app models questions generically
 * so the AI tutor can generate, explain, and adapt to any of them.
 */

/** Top-level SAT sections. */
export type SatSection = "reading-writing" | "math";

/** Difficulty bands used for adaptive practice. */
export type Difficulty = "easy" | "medium" | "hard";

/** A single multiple-choice answer option. */
export interface AnswerOption {
  /** Stable id, e.g. "A" | "B" | "C" | "D". */
  id: string;
  text: string;
}

/** A single SAT-style question. */
export interface Question {
  id: string;
  section: SatSection;
  /** Fine-grained skill, e.g. "command-of-evidence", "linear-equations". */
  skill: string;
  difficulty: Difficulty;
  /** The prompt / passage / problem statement. May contain LaTeX for math. */
  prompt: string;
  /** Optional passage text for Reading & Writing questions. */
  passage?: string;
  options: AnswerOption[];
  /** The correct option id. */
  correctOptionId: string;
  /** Concise explanation of why the correct answer is correct. */
  explanation: string;
  /** Estimated time in seconds the College Board suggests. */
  timeLimitSeconds?: number;
  /** Whether this question was generated by the AI tutor. */
  aiGenerated?: boolean;
}

/** A user's attempt at a question. */
export interface AnswerRecord {
  questionId: string;
  selectedOptionId: string;
  correct: boolean;
  /** Milliseconds the user spent on the question. */
  timeSpentMs: number;
  answeredAt: string; // ISO-8601
}

/** A practice session (a set of questions taken in one sitting). */
export interface PracticeSession {
  id: string;
  startedAt: string;
  endedAt?: string;
  section: SatSection;
  answers: AnswerRecord[];
}

/** Per-skill proficiency estimate (0-100). */
export interface SkillScore {
  skill: string;
  section: SatSection;
  /** 0-100 proficiency estimate. */
  score: number;
  /** Number of answered questions backing this estimate. */
  sampleSize: number;
  /** ISO-8601 date of the most recent answer for this skill. */
  lastPracticedAt: string;
}

/** A chat message in the AI tutor conversation. */
export interface TutorMessage {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  /** Optional structured payload (e.g. a generated question). */
  payload?: {
    question?: Question;
  };
  createdAt: string;
}

/** The AI tutor's system configuration. */
export interface TutorConfig {
  /** Model identifier, e.g. "gpt-4o-mini". */
  model: string;
  /** Max tokens for a single completion. */
  maxTokens: number;
  /** Sampling temperature (0-2). Lower = more deterministic. */
  temperature: number;
}
